### ISSUE TITLE
Will pg_dbms_job be available as a rpm package

### ISSUE THREAD

**Issue by Mariane-Kiesewetter** [MigOpsRepos/pg_dbms_job#1]
Hi,

Just a quick question.
Will pg_dbms_job also be available as a rpm package?
I have some servers where I don't have the oppertunity to connect with git.

Thanks in advance

**Comment by darold** [comment]
I will check that.

**Comment by Eric-zch** [comment]
I see pg_dbms_job from https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-8-x86_64/ 
Thank you.
@darold

**Comment by gilles-migops** [comment]
Oh great! Good news.
