### ISSUE TITLE
Password Logging

### ISSUE THREAD

**Issue by rsabankar** [MigOpsRepos/pg_dbms_job#10]
Logging Passwords is considered as a huge security and need to address this at the earliest to make use of this extension in production. Please help fixing the issue.

Thank you

**Comment by darold** [comment]
@rsabankar , can you elaborate please? Or does this issue is actually related to the credcheck extension?

**Comment by rsabankar** [comment]
Thanks @darold, This is not related to credcheck extension. After we install pg_dbms_job extension and configure the changes to work for a particular database , starting the pg_dbms_job spools the configuration parameters such as dbhost,port, username, password and logs the details in /tmp/pg_dbms_job.log file. Exposing the username and password in plain text will be a risk and to fix this we may need to make relevant changes to the perl executable (pg_dbms_job) and avoid this logging.

**Comment by darold** [comment]
Got it, commit 62d2d00 fixes this issue.

**Comment by rsabankar** [comment]
Thank you.
