### ISSUE TITLE
how to install pg_dbms_job on windows 10 ?

### ISSUE THREAD

**Issue by Cess113** [MigOpsRepos/pg_dbms_job#2]
Hello Gilles
Is there any chance to install pg_dbms_job on a windows 10 platform ?
Any guideline/procedure will be highly appreciated.
Thanks in advanced.
Edouard

**Comment by darold** [comment]
I don't know, I will try it and let you know.

**Comment by darold** [comment]
I'm closing the issue, it won't be supported unless someone makes this port.
