### ISSUE TITLE
Keeping entries in the table for the duration of the task

### ISSUE THREAD

**Issue by Jagrab3** [MigOpsRepos/pg_dbms_job#3]
Hi,
is it possible to change the behavior of entries about tasks in tables? 
This behavior is completely different from oracle

Asynchronous tasks:
Currently, when the job is running, a record in the table does not exist. Appears when the quest ends.
Example:

do
$$
declare
j bigint;
begin 
j:=dbms_job.submit('begin perform pg_sleep(30); end;');	
end;
$$

Monitor: when record appears....
SELECT * FROM dbms_job.all_async_jobs;
You can see the session:
select * from pg_stat_activity where query like '%pg_sleep(30)%' and pid<>pg_backend_pid();

Scheduled tasks:
The entry in the table remains until the task starts, then the record disappears from the table.

The idea is to be able to monitor job tables from inside the job.

Regards Peter

**Comment by darold** [comment]
Hi,

Right, to monitor the running jobs there is the pg_stat_activity view, you can filter on the application_name column. When it ends dbms_job.all_scheduler_job_run_details. Unlike Oracle, with PG it is possible to see the running job in pg_stat_activity so I've not seen the interest to duplicate the information especially that updating the status in the jobs table will introduce lot of bloat in case of heavy load. 

What are you looking for information that is not in pg_stat_activity? And  what Oracle compatibility issue you want to solve exactly (the query could help)?

**Comment by Jagrab3** [comment]
Hello.
The idea is to be able to check the existence of the performed task against the dbms_job tables.
The idea is to have an entry in the dbms_job.all_async_jobs table for the entire duration of the task.
Yes, it's done in Oracle, when you run the task, the run time appears in the this_date column. The entry is for the entire duration of the job running. In this case, it is possible to perform tasks on it, e.g. stopping.
Your solution allows you to trigger a task that works, but nowhere can you see what tasks are running at the moment. It is only possible to see scheduled tasks and those that have finished running.
pg_stat_activity is not the best place to monitor as the session is not the same as a task. We can stop the job, but the session will remain.
What's more, when I run a task, I want to be able to control it, that's what dbms_job.% Tables should be used for, not searching in database sessions.
I am currently working on the migrate of data warehouse  mechanisms from Oracle to postgresql, and more precisely on the task manager that will allow you to run processing trees.
Your implementation of dbms_job would be perfect if the behavior of the tables was consistent with what is in the Oracle database - that is, the currently running task has its entry in the table throughout its operation.
I assumed that since you created a tool that matches Oracle's nomenclature, it also matches functionality, unfortunately it is not.

**Comment by darold** [comment]
I understand, the problem is that the Oracle MVCC and PostgreSQL's one are different especially for update this is why I have chosen this implementation. But I agree that if there is not huge work on the dbms_job.all_async_jobs we could have the same behavior than with oracle. We could have a default mode a la Oracle and a high load that could be activated to have the current behavior.

I don't have this need for the moment so it is a very low priority but if your company want to sponsor this feature it could be done faster.

**Comment by Jagrab3** [comment]
Thanx Gilles,

I've already done the modification.

Now it works, how expected.

Once again thanx for this extension.

**Comment by Jagrab3** [comment]
[pg_dbms_job.zip](https://github.com/MigOpsRepos/pg_dbms_job/files/8238600/pg_dbms_job.zip)

**Comment by darold** [comment]
Excellent! Can you please create a pull request? It will be easier to review and apply.

**Comment by Jagrab3** [comment]
I also turned off the transaction management from the perl script. A forced transaction from the script level did not hinder the transaction management from the task level.

I will try to do a pull request, I have never done that;).

**Comment by Jagrab3** [comment]
Unfortunately, it looks like I don't have permission to do branch, can you check it once directly from this file? Only 1 file is changed
[pg_dbms_job.zip](https://github.com/MigOpsRepos/pg_dbms_job/files/8239391/pg_dbms_job.zip)
.

**Comment by darold** [comment]
Ok, I will use your archive. Thanks.

**Comment by darold** [comment]
Commit 523952b applies your patch.
