### ISSUE TITLE
Running on standby causes readonly connection error

### ISSUE THREAD

**Issue by mingravity** [MigOpsRepos/pg_dbms_job#4]
Hi,

we run Pg in a clustered environment using patroni. We want to run the daemon on each of the Pg nodes connecting to local server (localhost) but will only execute if it is primary (we can handle the primary check in the plpgsql job itself).
However the daemon on the secondary keep throwing "cannot execute UPDATE in read-only transaction". This is expected.
So
1) Is there a way to stop the daemon throwing that error and just sit doing nothing while the node is in recovery?
2) Is there an inbuilt log rotation?

**Comment by darold** [comment]
Commits 9b51d6d and 6827de5 add both features. Here are the commits comments:
```
    Allow pg_dbms_job to run on a standby server without reporting error.
    The daemon detects that it is running on a standby and disconnect
    immediately, it will try to connect 3 seconds later.
```
```
    Allow strftime() escapes in log filename, for example to have a log file
    per week day use %a in the file name.
    
    Add new configuration directive log_truncate_on_rotation to truncate file
    on rotation. When activated an existing log file with the same name as the
    new log file will be truncated rather than appended to. But such truncation
    only occurs on time-driven rotation, not on restarts.
```
