### ISSUE TITLE
 pg_dbms_job  does not work when restarting PG without killing the process of  pg_dbms_job

### ISSUE THREAD

**Issue by longforrich** [MigOpsRepos/pg_dbms_job#7]
# How to?
first
adding a new job,like

 SELECT dbms_job.submit(
  'INSERT INTO test1(id) SELECT GENERATE_SERIES(1,50);', -- what
  LOCALTIMESTAMP + '3 seconds'::interval, -- start the job in 3 seconds
  'LOCALTIMESTAMP + ''6 seconds''::interval' -- repeat the job every 6 seconds
 );

Second
pg_ctl -D xxx stop or kill -9 xxx

Third
pg_ctl -D xxx start

Final
Neither current job nor newly added job is working

DEBUG log
2022-07-21 18:51:54 [13550]: [810] DEBUG:  Found 0 asynchronous jobs to run
2022-07-21 18:51:54 [13550]: [705] DEBUG:  Get scheduled jobs to run
2022-07-21 18:51:54 [13550]: [741] DEBUG:  Found 1 scheduled jobs to run
2022-07-21 18:51:57 [13550]: [810] DEBUG:  Found 0 asynchronous jobs to run
2022-07-21 18:51:57 [13550]: [705] DEBUG:  Get scheduled jobs to run
2022-07-21 18:51:57 [13550]: [741] DEBUG:  Found 0 scheduled jobs to run

no log of "executing job xxx"

# Looking for problems
see function get_scheduled_jobs in the perl file of pg_dbms_job
...
if (!defined $sth)
{
	dprint('ERROR', "can't prepare statement, $DBI::errstr");
        $config_invalidated = 1 if (!$SINGLE); // <--- If error occurs, we set $config_invalidated = 1
        return %alljobs;
 }
...

see the call of get_scheduled_jobs
...
if ($scheduled_count || $startup)
{
   %SCHEDULED_JOBS = get_scheduled_jobs();
   $previous_scheduled_exec = time;
  if ($config_invalidated) { // <--- do loop next time
     sleep(3);
     $startup = 1;
     next;
  }
}
$config_invalidated = 0; // <---- here is reset flag
...

so...if we stop PG without kill pg_dbms_job, $config_invalidated will be set to 1
in get_scheduled_jobs. and we have no chance to modify $config_invalidated

# Change the code
I add $config_invalidated = 0 before "return %alljobs;" in get_scheduled_jobs
I don't know if this is the right thing to do?

**Comment by darold** [comment]
Commit 2b82948 apply your patch, not at the same place but this is the same.
