### ISSUE TITLE
One question regarding quote_literal

### ISSUE THREAD

**Issue by Eric-zch** [MigOpsRepos/pg_dbms_job#8]
I have one question about the use of quote_literal.
In source file [pg_dbms_job--1.3.0.sql](https://github.com/MigOpsRepos/pg_dbms_job/blob/main/sql/pg_dbms_job--1.3.0.sql)
```
CREATE PROCEDURE dbms_job.interval(
		jobid           IN  bigint,
		job_interval  IN  text)
    LANGUAGE PLPGSQL 
    AS $$
(omit)
        UPDATE dbms_job.all_scheduled_jobs SET interval = quote_literal(job_interval) WHERE job = jobid;
(omit)
END;
$$;


CREATE FUNCTION dbms_job.submit(
		jobid         OUT   bigint,
		what          IN    text,
		next_date     IN    timestamp(0) with time zone DEFAULT current_timestamp,
		job_interval  IN    text DEFAULT NULL,
		no_parse      IN    boolean DEFAULT false)
    RETURNS bigint
    LANGUAGE PLPGSQL
    AS $$
(omit)
    IF job_interval IS NOT NULL THEN
        INSERT INTO dbms_job.all_scheduled_jobs (what,next_date,interval) VALUES ($2,$3,$4) RETURNING job INTO jobid;
    ELSE
(omit)
END;
$$;

```

Why use quote_literal(job_interval) in dbms_job.interval, and not use quote_literal($4) in dbms_job.submit.

**Comment by darold** [comment]
The use of quote_literal() is only relevant with dynamic SQL. Saying that it look like the dbms_job.interval() function is buggy, the UPDATE statement should be dynamic. I will fix that ASAP, thanks for the report.

**Comment by darold** [comment]
Last release v1.4.0 include the fix for this issue.
